pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
        }
    }
    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    
    stages {
        stage('Git Pull') {
            steps {
                git 'https://github.com/anpolyakov/final-project'
            }
        }
        stage('Terraform init') {
            steps {
                dir("terraform") {
                    sh 'terraform init'
                }
            }
        }
        stage('Terraform plan and apply') {
            steps {
                dir("terraform") {
                    sh 'terraform plan -input=false -out tfplan'
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                    sh 'terraform apply --auto-approve'
                }
            }
        }
        stage('Ansible provisoning and Deploy Java App') {
            steps {
                sh 'sleep 30s'
                    ansiblePlaybook( 
                    playbook: 'ansible/provisoning.yml',
                    inventory: 'terraform/inventory',
                    credentialsId: 'aws_key',
                    disableHostKeyChecking: false,
                    extras: '-e @aws_variables.yml')
            }
        }
    }
}