---
- name: Setup Maven Environment
  gather_facts: False
  become: yes
  hosts: maven
  vars_files:
    - /var/lib/jenkins/workspace/Final Project/aws_variables.yml
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

  tasks:

  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present

  - name: Ensure pip packages is present
    pip:
      name: 
      - docker-py
      - boto3
      - botocore

  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project

  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/maven
      name: maven-image

  - name: Create a maven container
    docker_container:
      name: maven-container
      image: maven-image
      detach: yes
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp:/tmp
    
  - name: Add container to inventory
    add_host:
      name: maven-container
      ansible_connection: docker
      ansible_docker_extra_args: "-H=tcp://35.159.23.110:4243"
    changed_when: false

  - name: Remove old releases Java App
    file:
      path: /tmp/boxfuse-sample-java-war-hello
      state: absent

  - name: Clone Java App
    command: docker exec -it maven-container bash -c "git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello /tmp/boxfuse-sample-java-war-hello"

  - name: Build Java App
    command: docker exec -it maven-container bash -c "mvn package -f /tmp/boxfuse-sample-java-war-hello/pom.xml"
    
  - name: Create an empty bucket
    aws_s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: final-project-bucket
      region: eu-central-1
      mode: create
      permission: private

  - name: Copy artefact to bucket
    aws_s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: final-project-bucket
      region: eu-central-1
      object: hello-1.0.war
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      mode: put

- name: Setup Tomcat Environment
  gather_facts: False
  become: yes
  hosts: tomcat

  tasks:
  
  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present
  
  - name: Ensure pip packages is present
    pip:
      name: 
      - docker-py
      - boto3
      - botocore

  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project
  
  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/tomcat
      name: tomcat-image

  - name: Create a tomcat container
    docker_container:
      name: tomcat-container
      image: tomcat-image
      published_ports: 8080:8080
      detach: yes
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp/:/usr/local/tomcat/webapps

  - name: Download artefact to tomcat webroot
    aws_s3:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      bucket: final-project-bucket
      region: eu-central-1
      object: hello-1.0.war
      dest: /tmp/hello-1.0.war
      mode: get




  
    
