---
- name: Setup Maven Environment
  gather_facts: False
  become: yes
  hosts: maven

  tasks:

  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project

  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/maven
      name: maven
    


- name: Setup Tomcat Environment
  gather_facts: False
  become: yes
  hosts: tomcat

  tasks:
  
  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started