---
- name: Setup Maven Environment
  gather_facts: False
  become: yes
  hosts: maven

  tasks:

  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present

  - name: Ensure docker-py is present
    pip:
      name: 
      - docker-py

  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project

  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/maven
      name: maven-image

  - name: Create a maven container
    docker_container:
      name: maven-container
      image: maven-image
      detach: yes
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    
  - name: Add container to inventory
    add_host:
      name: maven-container
      ansible_connection: docker
    changed_when: false

  - name: Run commands in maven container
    apt:
      - nmap
    update_cache: yes
    state: present
    become: yes
    become_user: root
    delegate_to: maven-container
      

- name: Setup Tomcat Environment
  gather_facts: False
  become: yes
  hosts: tomcat

  tasks:
  
  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present
  
  - name: Ensure docker-py is present
    pip:
      name: 
      - docker-py
  
  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project
  
  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/tomcat
      name: tomcat