---
- name: Setup Maven Environment
  gather_facts: False
  become: yes
  hosts: maven

  tasks:

  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

  - name: Ensure pip is present
    apt:
      name: python3-pip
      state: present

  - name: Ensure docker-py is present
    pip:
      name: 
      - docker-py

  - name: Git Clone
    git:
      repo: https://github.com/anpolyakov/final-project
      dest: /tmp/final-project

  - name: Create docker image
    docker_image:
      path: /tmp/final-project/docker/maven
      name: maven
    


- name: Setup Tomcat Environment
  gather_facts: False
  become: yes
  hosts: tomcat

  tasks:
  
  - name: Ensure docker is present
    apt:
      name: docker.io
      update_cache: yes
      state: present

  - name: Ensure docker is started
    service:
      name: docker
      state: started

      - name: Ensure pip is present
      apt:
        name: python3-pip
        state: present
  
    - name: Ensure docker-py is present
      pip:
        name: 
        - docker-py
  
    - name: Git Clone
      git:
        repo: https://github.com/anpolyakov/final-project
        dest: /tmp/final-project
  
    - name: Create docker image
      docker_image:
        path: /tmp/final-project/docker/tomcat
        name: tomcat